import type { ColorScheme, VariantConfig } from './types';

export const ANALYSIS_COLOR_SCHEMES: Record<string, ColorScheme> = {
  similarity: {
    gradient: 'from-rose-500 to-rose-600',
    lightGradient: 'from-rose-50 to-rose-100',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    selectedBorder: 'border-rose-500',
    selectedBg: 'bg-rose-50',
    selectedRing: 'ring-rose-200',
    icon: 'text-rose-600',
    selectedIcon: 'text-white',
    title: 'text-rose-700',
    iconBg: 'bg-rose-500',
    featureBg: 'bg-rose-50',
    featureBorder: 'border-rose-200',
    accent: 'text-rose-600',
  },
  kmeans: {
    gradient: 'from-green-500 to-green-600',
    lightGradient: 'from-green-50 to-green-100',
    bg: 'bg-green-50',
    border: 'border-green-200',
    selectedBorder: 'border-green-500',
    selectedBg: 'bg-green-50',
    selectedRing: 'ring-green-200',
    icon: 'text-green-600',
    selectedIcon: 'text-white',
    title: 'text-green-700',
    iconBg: 'bg-green-500',
    featureBg: 'bg-green-50',
    featureBorder: 'border-green-200',
    accent: 'text-green-600',
  },
  dbscan: {
    gradient: 'from-purple-500 to-purple-600',
    lightGradient: 'from-purple-50 to-purple-100',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    selectedBorder: 'border-purple-500',
    selectedBg: 'bg-purple-50',
    selectedRing: 'ring-purple-200',
    icon: 'text-purple-600',
    selectedIcon: 'text-white',
    title: 'text-purple-700',
    iconBg: 'bg-purple-500',
    featureBg: 'bg-purple-50',
    featureBorder: 'border-purple-200',
    accent: 'text-purple-600',
  },
  agglomerative: {
    gradient: 'from-orange-500 to-orange-600',
    lightGradient: 'from-orange-50 to-orange-100',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    selectedBorder: 'border-orange-500',
    selectedBg: 'bg-orange-50',
    selectedRing: 'ring-orange-200',
    icon: 'text-orange-600',
    selectedIcon: 'text-white',
    title: 'text-orange-700',
    iconBg: 'bg-orange-500',
    featureBg: 'bg-orange-50',
    featureBorder: 'border-orange-200',
    accent: 'text-orange-600',
  },
};

export const VARIANT_CONFIGS: Record<string, VariantConfig> = {
  compact: {
    card: 'hover:scale-[1.01]',
    header: 'p-4',
    iconSize: 'w-12 h-12',
    iconInner: 'h-6 w-6',
    title: 'text-base',
    description: 'text-xs',
    spacing: 'space-y-3',
  },
  modal: {
    card: 'hover:scale-[1.02]',
    header: 'p-6',
    iconSize: 'w-16 h-16',
    iconInner: 'h-8 w-8',
    title: 'text-lg',
    description: 'text-sm',
    spacing: 'space-y-4',
  },
  default: {
    card: 'hover:scale-[1.02]',
    header: 'p-6',
    iconSize: 'w-16 h-16',
    iconInner: 'h-8 w-8',
    title: 'text-lg',
    description: 'text-sm',
    spacing: 'space-y-4',
  },
};

export const GRID_CONFIGS: Record<string, string> = {
  compact: 'grid grid-cols-1 md:grid-cols-2 gap-4',
  modal: 'grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6',
  default: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6',
};
